weights: ./runs/train/sizes_try_final_imgw/weights/last.pt
cfg: ''
data: visdrone.yaml
hyp: data/hyp.scratch.tiny.yaml
epochs: 369
batch_size: 20
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: true
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 16
project: runs/train
entity: null
name: sizes_try_final_imgw
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: runs/train/sizes_try_final_imgw
total_batch_size: 20
